
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author alexandrezamberlan
 */
public class ClienteJogador2 extends javax.swing.JFrame {
    // Mantenha estas variáveis como membros da classe
    Socket socket_jogador1;
    ObjectOutputStream saida;
    ObjectInputStream entrada;
    Componente c;
    
    // 1. CONSTRUTOR PADRÃO (sem parâmetros - apenas para o main, se necessário)
    public ClienteJogador2() {
        initComponents();
        // Não inicie a thread de comunicação aqui!
    }

    // 2. NOVO CONSTRUTOR: Recebe os objetos de conexão
    public ClienteJogador2(Socket socket, ObjectOutputStream saida, ObjectInputStream entrada) {
        initComponents();
        
        // Atribui os objetos de conexão recebidos
        this.socket_jogador1 = socket;
        this.saida = saida;
        this.entrada = entrada;
        
        // Inicia a thread de comunicação AGORA
        iniciarComunicacao();
    }
    
    public void iniciarComunicacao() {
             new Thread() {
                @Override
                public void run() {
                    try {
                        while (true) {
                            c = (Componente) entrada.readObject();
                            //se for jogador
                            if (c.tipo == Componente.JOGADOR) {
                                jButtonJogador1.setBounds(c.x, c.y, c.largura, c.altura);
                            } //se for fruta
                            else if (c.tipo == Componente.FRUTA) {
                                jButtonFruta.setBounds(c.x, c.y, c.largura, c.altura);
                            }
                        }
                    } catch (Exception e) {
                        // Trate o erro de conexão aqui, talvez exibindo um JOptionPane
                        System.out.println("Erro na comunicação: " + e.getMessage());
                        // Opcional: Voltar para a tela de login ou fechar
                        JOptionPane.showMessageDialog(null, "Conexão perdida com o servidor.", "Erro de Conexão", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }.start();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelJogador2 = new javax.swing.JPanel();
        jButtonJogador1 = new javax.swing.JButton();
        jButtonFruta = new javax.swing.JButton();
        jButtonJogador2 = new javax.swing.JButton();
        jLabel_placar1 = new javax.swing.JLabel();
        jLabel_placar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogador 2 - CLIENTE");

        jButtonJogador1.setText("j1");
        jButtonJogador1.setFocusable(false);

        jButtonFruta.setBackground(new java.awt.Color(255, 204, 0));
        jButtonFruta.setText("@");
        jButtonFruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonFrutaKeyPressed(evt);
            }
        });

        jButtonJogador2.setText("j2");
        jButtonJogador2.setFocusable(false);

        jLabel_placar1.setText("jLabel1");

        jLabel_placar2.setText("jLabel1");

        javax.swing.GroupLayout jPanelJogador2Layout = new javax.swing.GroupLayout(jPanelJogador2);
        jPanelJogador2.setLayout(jPanelJogador2Layout);
        jPanelJogador2Layout.setHorizontalGroup(
            jPanelJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJogador2Layout.createSequentialGroup()
                .addGroup(jPanelJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonJogador2))
                    .addGroup(jPanelJogador2Layout.createSequentialGroup()
                        .addGroup(jPanelJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJogador2Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jButtonFruta))
                            .addGroup(jPanelJogador2Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jButtonJogador1))
                            .addGroup(jPanelJogador2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_placar1)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel_placar2)))
                        .addGap(0, 184, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelJogador2Layout.setVerticalGroup(
            jPanelJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJogador2Layout.createSequentialGroup()
                .addGroup(jPanelJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_placar1)
                    .addComponent(jLabel_placar2))
                .addGap(28, 28, 28)
                .addComponent(jButtonJogador1)
                .addGap(64, 64, 64)
                .addComponent(jButtonFruta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButtonJogador2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJogador2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFrutaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonFrutaKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case 37:
                //System.out.println("indo para esquerda");
                Movimenta.irEsquerda(jButtonJogador2);
                break;
            case 38:
                //System.out.println("indo para cima");
                Movimenta.irCima(jButtonJogador2);
                break;
            case 39:
                //System.out.println("indo para direita");
                Movimenta.irDireita(jButtonJogador2, jPanelJogador2.getBounds().width);
                break;
            case 40:
                //System.out.println("indo para baixo");
                Movimenta.irBaixo(jButtonJogador2, jPanelJogador2.getBounds().height);
                break;
        }
        if (Movimenta.pegou(jButtonJogador2, jButtonFruta)) {
            // J2 PEGOU: APENAS ENVIA MENSAGEM AO SERVIDOR (usando o tipo FRUTA).
            // Não altera placar nem fruta localmente.
            try {
                saida.flush();
                Componente cPegou = new Componente(0, 0, 0, 0, Componente.FRUTA,2); // ID JOGADOR 2
                saida.writeObject(cPegou);

                } catch (Exception e) {
                    System.out.println("Erro ao reportar que a fruta foi pega!");
                    }
        }
        // Envio da posição J2 para Servidor J1
        try {
            saida.flush();
            Componente cPosicao = new Componente(
                jButtonJogador2.getBounds().x,
                jButtonJogador2.getBounds().y,
                jButtonJogador2.getBounds().width,
                jButtonJogador2.getBounds().height,
                Componente.JOGADOR, // Tipo JOGADOR
                2 // ID JOGADOR 2
            );
            saida.writeObject(cPosicao);
            } catch (Exception e) {
                System.out.println("Erro ao enviar o jogador 2");
        }
    }//GEN-LAST:event_jButtonFrutaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteJogador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteJogador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteJogador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteJogador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    Socket socket_jogador1;
    ObjectOutputStream saida;
    ObjectInputStream entrada;
    Componente c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFruta;
    private javax.swing.JButton jButtonJogador1;
    private javax.swing.JButton jButtonJogador2;
    private javax.swing.JLabel jLabel_placar1;
    private javax.swing.JLabel jLabel_placar2;
    private javax.swing.JPanel jPanelJogador2;
    // End of variables declaration//GEN-END:variables
}
